### ISSUE TITLE
아이디네이션 1차

### ISSUE THREAD

**Issue by hojae-lee** [sandbox-tf-studio/what-idea-is-good#1]
## issue

어떤 아이디어를 만드는 과정 또는 찾는 과정

**Comment by Hyejinijini** [comment]
<h2>1. 인스타그램 만들기</h2>

**1. 기능**
- 회원가입 및 로그인
- 사용자 사진/동영상 업로드
- 좋아요 및 댓글 달기
- 알림 수신 기능
- 검색 기능
<br />

**2. 기술**
- 프론트엔드: React, JavaScript, Tailwindcss
<br />

**3. 추후**
- 스토리 기능
- 사용자 간 1:1 채팅 기능
- 다국어 지원
- 라이브 방송 등

**Comment by hojae-lee** [comment]
> ## 1. 인스타그램 만들기
> **1. 기능**
> 
> * 회원가입 및 로그인
> * 사용자 사진/동영상 업로드
> * 좋아요 및 댓글 달기
> * 알림 수신 기능
> * 검색 기능
> 
> 
> **2. 기술**
> 
> * 프론트엔드: React, JavaScript, Tailwindcss
> 
> 
> **3. 추후**
> 
> * 스토리 기능
> * 사용자 간 1:1 채팅 기능
> * 다국어 지원
> * 라이브 방송 등

해당 내용 PR 로 올려주세요~~!!
